#!/bin/bash
# Auto-generated by init-project-search.sh
# Updates vector embeddings for semantic search via HTTP API

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"
VECTOR_SEARCH_ROOT="/Users/hunter/code/ai_agency/shared/mcp-servers/seekr"
VECTOR_SEARCH_PORT="${VECTOR_SEARCH_HTTP_PORT:-3456}"
VECTOR_SEARCH_URL="http://localhost:$VECTOR_SEARCH_PORT"
LOG_FILE="$REPO_ROOT/.mcp/vector-search/update.log"

echo "🔍 Vector Search Update Started: $(date)" | tee -a "$LOG_FILE"

# Function to check if HTTP server is running
check_server() {
    curl -s "$VECTOR_SEARCH_URL/health" >/dev/null 2>&1
    return $?
}

# Function to start the HTTP server
start_server() {
    echo "📡 Starting vector-search HTTP server..." | tee -a "$LOG_FILE"
    cd "$VECTOR_SEARCH_ROOT"
    VECTOR_SEARCH_HTTP_PORT=$VECTOR_SEARCH_PORT nohup node build/http-server.js >> "$LOG_FILE" 2>&1 &
    echo $! > "$REPO_ROOT/.mcp/vector-search/server.pid"

    # Wait for server to start (max 30 seconds)
    for i in {1..30}; do
        if check_server; then
            echo "✅ HTTP server started on port $VECTOR_SEARCH_PORT" | tee -a "$LOG_FILE"
            return 0
        fi
        sleep 1
    done
    echo "❌ HTTP server failed to start" | tee -a "$LOG_FILE"
    return 1
}

# Check if server is running, start if needed
if ! check_server; then
    start_server || exit 1
fi

# Call the index_codebase tool via HTTP API
echo "📊 Indexing codebase: $REPO_ROOT" | tee -a "$LOG_FILE"

RESPONSE=$(curl -s -X POST "$VECTOR_SEARCH_URL/call-tool" \
    -H "Content-Type: application/json" \
    -d "{\"tool\": \"index_codebase\", \"arguments\": {\"project_path\": \"$REPO_ROOT\"}}")

# Check if request succeeded
if echo "$RESPONSE" | grep -q '"success":true'; then
    FILES_INDEXED=$(echo "$RESPONSE" | grep -o '"filesIndexed":[0-9]*' | cut -d: -f2)
    CHUNKS_CREATED=$(echo "$RESPONSE" | grep -o '"chunksCreated":[0-9]*' | cut -d: -f2)
    echo "✅ Vector search indexed: $FILES_INDEXED files, $CHUNKS_CREATED chunks" | tee -a "$LOG_FILE"
else
    ERROR=$(echo "$RESPONSE" | grep -o '"error":"[^"]*"' | cut -d: -f2 | tr -d '"')
    echo "❌ Vector search update failed: $ERROR" | tee -a "$LOG_FILE"
    echo "Response: $RESPONSE" >> "$LOG_FILE"
fi

echo "✅ Vector Search Update Complete: $(date)" | tee -a "$LOG_FILE"
