#!/bin/bash
# Initialize code-graph-rag for a project
# Usage: init-project-graph.sh <project-path> [--group <group>] [--no-hook]

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration (dynamic - uses script location)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CODE_GRAPH_ROOT="$SCRIPT_DIR"
REGISTRY_FILE="$SCRIPT_DIR/infrastructure/registry/projects.toon"
LOGS_DIR="$SCRIPT_DIR/infrastructure/logs"

log() { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $1"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }
log_header() { echo -e "${CYAN}$1${NC}"; }

print_header() {
    echo ""
    echo "=========================================="
    echo "$1"
    echo "=========================================="
    echo ""
}

print_section() {
    echo ""
    log_header "━━━ $1 ━━━"
    echo ""
}

# Parse arguments
NO_HOOK=false
PROJECT_PATH=""
GROUP=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --no-hook)
            NO_HOOK=true
            shift
            ;;
        --group)
            GROUP="$2"
            shift 2
            ;;
        *)
            if [ -z "$PROJECT_PATH" ]; then
                PROJECT_PATH="$1"
            fi
            shift
            ;;
    esac
done

# Usage
if [ -z "$PROJECT_PATH" ]; then
    print_header "Code-Graph-RAG - Project Initialization"
    echo "Sets up code-graph-rag for a project"
    echo ""
    echo "Usage: $0 <project-path> [options]"
    echo ""
    echo "Arguments:"
    echo "  project-path         Path to the project directory"
    echo ""
    echo "Options:"
    echo "  --group <name>       Add to a shared group graph (e.g., 'mcp-servers')"
    echo "  --no-hook            Skip installing post-commit hook"
    echo ""
    echo "Examples:"
    echo "  $0 /path/to/my-project"
    echo "  $0 ~/code/my-project --group mcp-servers"
    echo "  $0 ~/code/my-project --no-hook"
    echo ""
    echo "This script will:"
    echo "  ✓ Initialize code-graph database for the project"
    echo "  ✓ Create update script in .mcp/codebase-intelligence/code-graph-rag/"
    echo "  ✓ Install post-commit hook (unless --no-hook)"
    echo "  ✓ Build initial code graph"
    echo "  ✓ Register project in code-graph registry"
    echo ""
    exit 1
fi

PROJECT_PATH="$(cd "$PROJECT_PATH" && pwd)"
PROJECT_NAME="$(basename "$PROJECT_PATH")"

print_header "🔗 Initializing Code-Graph for: $PROJECT_NAME"

#
# Step 1: Validate Project
#
print_section "Validating Project"

if [ ! -d "$PROJECT_PATH" ]; then
    log_error "Directory does not exist: $PROJECT_PATH"
    exit 1
fi

if [ ! -d "$PROJECT_PATH/.git" ]; then
    log_error "Not a git repository: $PROJECT_PATH"
    log_warning "Initialize git first: cd $PROJECT_PATH && git init"
    exit 1
fi

log_success "Project validated: $PROJECT_PATH"

#
# Step 2: Check Dependencies
#
print_section "Checking Dependencies"

# Check Memgraph
log "Checking Memgraph..."
if ! docker ps | grep -q memgraph; then
    log_warning "Memgraph not running. Starting..."
    (cd "$CODE_GRAPH_ROOT" && docker compose up -d) || {
        log_error "Failed to start Memgraph"
        exit 1
    }
    sleep 5
fi
log_success "Memgraph is running"

#
# Step 3: Initialize Directory Structure
#
print_section "Initializing Code-Graph"

# Create .mcp/codebase-intelligence directory structure
log "Creating .mcp/codebase-intelligence/code-graph-rag directory..."
mkdir -p "$PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/logs"
mkdir -p "$LOGS_DIR"
log_success "Created directory structure"

# Add to .gitignore
log "Updating .gitignore..."
GITIGNORE="$PROJECT_PATH/.gitignore"

if [ ! -f "$GITIGNORE" ]; then
    touch "$GITIGNORE"
fi

if ! grep -q "^\.mcp/codebase-intelligence/" "$GITIGNORE" 2>/dev/null; then
    echo "" >> "$GITIGNORE"
    echo "# MCP codebase intelligence - all auto-generated/derived data" >> "$GITIGNORE"
    echo ".mcp/codebase-intelligence/" >> "$GITIGNORE"
    log_success "Added .mcp/codebase-intelligence/ to .gitignore"
else
    log "Already in .gitignore"
fi

# Determine database names
DB_PROJECT="codegraph_${PROJECT_NAME}"
DB_GROUP=""
if [ -n "$GROUP" ]; then
    DB_GROUP="codegraph_${GROUP}"
fi

log "Database: $DB_PROJECT"
[ -n "$DB_GROUP" ] && log "Group Database: $DB_GROUP"

# Create code-graph update script
log "Generating code-graph update script..."

cat > "$PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/update.sh" << SCRIPT_START
#!/bin/bash
# Auto-generated by init-project-graph.sh
# Updates code graphs at all configured levels

set -e

REPO_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && cd ../../.. && pwd)"
CODE_GRAPH_ROOT="$CODE_GRAPH_ROOT"
CENTRALIZED_LOG_DIR="$LOGS_DIR"
PROJECT_LOG_DIR="\$REPO_ROOT/.mcp/codebase-intelligence/code-graph-rag/logs"
LOCAL_LOG="\$REPO_ROOT/.mcp/codebase-intelligence/code-graph-rag/update.log"

mkdir -p "\$CENTRALIZED_LOG_DIR"
mkdir -p "\$PROJECT_LOG_DIR"

# Project configuration
PROJECT_NAME="$PROJECT_NAME"
GROUP="$GROUP"

DB_PROJECT="$DB_PROJECT"
DB_GROUP="$DB_GROUP"

# Update a single database
update_graph() {
    local db_name="\$1"
    local repo_path="\$2"
    local log_name="\$(echo "\$db_name" | sed 's/codegraph_//')"
    local level="\$3"  # "project", "group", or "scope"

    echo "📊 Updating \$db_name..."

    # Determine log location: project logs locally, group/scope logs centrally
    local log_file
    if [ "\$level" = "project" ]; then
        log_file="\$PROJECT_LOG_DIR/\${log_name}.log"
    else
        log_file="\$CENTRALIZED_LOG_DIR/\${log_name}.log"
    fi

    (
        cd "\$CODE_GRAPH_ROOT"
        source venv/bin/activate

        export MEMGRAPH_DATABASE="\$db_name"

        python -m codebase_rag.main start \\
            --repo-path "\$repo_path" \\
            --update-graph \\
            --no-confirm \\
            >> "\$log_file" 2>&1

        if [ \$? -eq 0 ]; then
            echo "✅ \$db_name updated successfully" | tee -a "\$LOCAL_LOG"
        else
            echo "❌ \$db_name update failed (check logs)" | tee -a "\$LOCAL_LOG"
        fi
    )
}

# Create symlinks from project logs to centralized logs for group
create_log_symlinks() {
    if [ -n "\$GROUP" ]; then
        local group_log="\$PROJECT_LOG_DIR/\${GROUP}.log"
        local group_target="\$CENTRALIZED_LOG_DIR/\${GROUP}.log"

        if [ ! -e "\$group_log" ] && [ -f "\$group_target" ]; then
            ln -sf "\$group_target" "\$group_log"
            echo "🔗 Created symlink: \${GROUP}.log → centralized"
        fi
    fi
}

# Main execution
echo "🔄 Code-Graph Update Started: \$(date)"

# Create symlinks for viewing all logs in one place
create_log_symlinks

# Update project graph
update_graph "\$DB_PROJECT" "\$REPO_ROOT" "project"

# Update group graph (if configured)
if [ -n "\$DB_GROUP" ] && [ -n "\$GROUP" ]; then
    GROUP_PATH="\$(dirname "\$REPO_ROOT")"
    update_graph "\$DB_GROUP" "\$GROUP_PATH" "group"
fi

echo "✅ Code-Graph Update Complete: \$(date)" | tee -a "\$LOCAL_LOG"
SCRIPT_START

chmod +x "$PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/update.sh"
log_success "Created code-graph-rag/update.sh"

# Create code-graph ignore file
if [ ! -f "$PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/ignore" ]; then
    log "Creating code-graph ignore file..."
    cat > "$PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/ignore" << 'IGNORE'
# Project-specific exclusions for code-graph
# Global exclusions are handled by code-graph-rag

# Exclude codebase intelligence artifacts from graph
.mcp/codebase-intelligence/

# Example: Exclude generated files
# generated/

# Example: Exclude specific directories
# scripts/temp/
IGNORE

    log_success "Created code-graph/ignore"
fi

#
# Step 4: Install Git Hook (unless --no-hook)
#
if [ "$NO_HOOK" = false ]; then
    print_section "Installing Git Hook"

    POSTCOMMIT_HOOK="$PROJECT_PATH/.git/hooks/post-commit"

    # Check if hook exists and has other content
    if [ -f "$POSTCOMMIT_HOOK" ]; then
        if grep -q "code-graph" "$POSTCOMMIT_HOOK"; then
            log "Post-commit hook already has code-graph configured"
        else
            log "Appending to existing post-commit hook..."
            cat >> "$POSTCOMMIT_HOOK" << 'HOOK_APPEND'

# Update code-graph (background)
CODE_GRAPH_SCRIPT="$(git rev-parse --show-toplevel)/.mcp/codebase-intelligence/code-graph-rag/update.sh"
if [ -f "$CODE_GRAPH_SCRIPT" ]; then
    "$CODE_GRAPH_SCRIPT" &
    echo "✅ Code-graph update started in background"
fi
HOOK_APPEND
            log_success "Appended code-graph to post-commit hook"
        fi
    else
        log "Installing post-commit hook..."
        cat > "$POSTCOMMIT_HOOK" << 'HOOK_NEW'
#!/bin/bash
# Auto-generated post-commit hook
# Updates code-graph after commit

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Update code-graph (background)
CODE_GRAPH_SCRIPT="$REPO_ROOT/.mcp/codebase-intelligence/code-graph-rag/update.sh"
if [ -f "$CODE_GRAPH_SCRIPT" ]; then
    "$CODE_GRAPH_SCRIPT" &
    echo "✅ Code-graph update started in background"
fi
HOOK_NEW
        chmod +x "$POSTCOMMIT_HOOK"
        log_success "Post-commit hook installed"
    fi
else
    log "Skipping post-commit hook installation (--no-hook)"
fi

#
# Step 5: Build Initial Code Graph
#
print_section "Building Initial Code Graph"

# Estimate processing time based on file count
echo -n "$(echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC}") Analyzing codebase"
FILE_COUNT=$(find "$PROJECT_PATH" -type f \( -name "*.py" -o -name "*.ts" -o -name "*.js" -o -name "*.tsx" -o -name "*.jsx" \) 2>/dev/null | wc -l | tr -d ' ')
echo " - done!"

# Rough estimate: ~100ms per file
ESTIMATED_SECONDS=$((FILE_COUNT / 10))
ESTIMATED_MINUTES=$((ESTIMATED_SECONDS / 60))

log "Found $FILE_COUNT code files"
if [ $ESTIMATED_MINUTES -gt 0 ]; then
    log "Estimated time: ~${ESTIMATED_MINUTES}-$((ESTIMATED_MINUTES + 2)) minutes"
else
    log "Estimated time: < 1 minute"
fi

echo ""
log "Building graph... (monitor progress: tail -f $PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/update.log)"
"$PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/update.sh" || {
    log_warning "Initial graph build had warnings (check logs)"
}

log_success "Code graph initialized"

#
# Step 6: Update Project Registry
#
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S")

# Ensure registry file exists
mkdir -p "$(dirname "$REGISTRY_FILE")"
if [ ! -f "$REGISTRY_FILE" ]; then
    cat > "$REGISTRY_FILE" << 'REGISTRY_HEADER'
# Code-Graph Project Registry
# Auto-updated by init-project-graph.sh
# Format: TOON (Tab-Organized Object Notation)

# Projects initialized with code-graph-rag
projects:
	# Example entry:
	# - name: my-project
	#   path: /path/to/project
	#   group: my-group
	#   databases: [codegraph_my-project, codegraph_my-group]
	#   initialized_at: 2024-12-01T14:30:00
REGISTRY_HEADER
fi

# Remove existing entry for this project
grep -v "path: $PROJECT_PATH$" "$REGISTRY_FILE" > "$REGISTRY_FILE.tmp" 2>/dev/null || cp "$REGISTRY_FILE" "$REGISTRY_FILE.tmp"
mv "$REGISTRY_FILE.tmp" "$REGISTRY_FILE"

# Build databases array
if [ -n "$DB_GROUP" ]; then
    DATABASES="[$DB_PROJECT, $DB_GROUP]"
else
    DATABASES="[$DB_PROJECT]"
fi

# Append new entry
cat >> "$REGISTRY_FILE" << ENTRY
	- name: $PROJECT_NAME
	  path: $PROJECT_PATH
	  group: "$GROUP"
	  databases: $DATABASES
	  initialized_at: $TIMESTAMP
ENTRY

log_success "Updated project registry"

#
# Step 7: Summary
#
print_header "✨ Code-Graph Setup Complete! ✨"

echo "Project: $PROJECT_NAME"
echo "Path: $PROJECT_PATH"
echo "Database: $DB_PROJECT"
[ -n "$DB_GROUP" ] && echo "Group Database: $DB_GROUP"
echo ""
echo "📦 Installed:"
echo "  ✅ .mcp/codebase-intelligence/code-graph-rag/ (update script, logs)"
if [ "$NO_HOOK" = false ]; then
    echo "  ✅ Post-commit hook"
fi
echo ""
echo "📝 Commands:"
echo "  Manual update: $PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/update.sh"
echo "  View graph:    http://localhost:3000 (Memgraph Lab)"
echo "  View logs:     tail -f $PROJECT_PATH/.mcp/codebase-intelligence/code-graph-rag/update.log"
echo ""
