#!/bin/bash
# Add a project to a shared code-graph group
# Usage: add-to-group.sh <project-path> <group-name>

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CODE_GRAPH_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOGS_DIR="$CODE_GRAPH_ROOT/infrastructure/logs"

log() { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $1"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }
log_header() { echo -e "${CYAN}$1${NC}"; }

print_header() {
    echo ""
    echo "=========================================="
    echo "$1"
    echo "=========================================="
    echo ""
}

print_section() {
    echo ""
    log_header "━━━ $1 ━━━"
    echo ""
}

# Usage
if [ "$#" -lt 2 ]; then
    print_header "Add Project to Code-Graph Group"
    echo "Adds a project to a shared code-graph group database"
    echo ""
    echo "Usage: $0 <project-path> <group-name>"
    echo ""
    echo "Arguments:"
    echo "  project-path    Path to the project directory"
    echo "  group-name      Name of the group (e.g., 'mcp-servers', 'life')"
    echo ""
    echo "Examples:"
    echo "  $0 ~/code/ai_agency/shared/mcp-servers/ai-gateway-mcp mcp-servers"
    echo "  $0 /path/to/my-project my-group"
    echo ""
    echo "Prerequisites:"
    echo "  - Project must already have code-graph initialized"
    echo "    (run init-code-graph.sh first)"
    echo ""
    echo "This script will:"
    echo "  ✓ Update the project's code-graph script to also update group graph"
    echo "  ✓ Build the group graph (indexes parent directory)"
    echo ""
    exit 1
fi

PROJECT_PATH="$(cd "$1" && pwd)"
PROJECT_NAME="$(basename "$PROJECT_PATH")"
GROUP="$2"

print_header "📂 Adding $PROJECT_NAME to group: $GROUP"

#
# Step 1: Validate Project
#
print_section "Validating Project"

if [ ! -d "$PROJECT_PATH" ]; then
    log_error "Directory does not exist: $PROJECT_PATH"
    exit 1
fi

if [ ! -f "$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh" ]; then
    log_error "Code-graph not initialized for this project"
    log_warning "Run init-code-graph.sh first: ./init-code-graph.sh $PROJECT_PATH"
    exit 1
fi

# Check if already in a group
if grep -q "DB_GROUP=" "$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh"; then
    EXISTING_GROUP=$(grep "DB_GROUP=" "$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh" | head -1 | cut -d'"' -f2 | sed 's/codegraph_//')
    if [ -n "$EXISTING_GROUP" ]; then
        log_warning "Project already in group: $EXISTING_GROUP"
        read -p "Replace with $GROUP? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log "Cancelled"
            exit 0
        fi
    fi
fi

log_success "Project validated: $PROJECT_PATH"

#
# Step 2: Check Dependencies
#
print_section "Checking Dependencies"

# Check Memgraph
log "Checking Memgraph..."
if ! docker ps | grep -q memgraph; then
    log_warning "Memgraph not running. Starting..."
    (cd "$CODE_GRAPH_ROOT" && docker compose up -d) || {
        log_error "Failed to start Memgraph"
        exit 1
    }
    sleep 5
fi
log_success "Memgraph is running"

#
# Step 3: Update Code-Graph Script
#
print_section "Updating Code-Graph Configuration"

DB_PROJECT="codegraph_${PROJECT_NAME}"
DB_GROUP="codegraph_${GROUP}"

log "Project database: $DB_PROJECT"
log "Group database: $DB_GROUP"

# Regenerate the update script with group support
log "Updating code-graph update script..."

cat > "$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh" << 'SCRIPT_START'
#!/bin/bash
# Auto-generated by add-to-group.sh
# Updates code graphs at project and group levels

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"
CODE_GRAPH_ROOT="/Users/hunter/code/ai_agency/shared/mcp-servers/code-graph-rag"
CENTRALIZED_LOG_DIR="$CODE_GRAPH_ROOT/infrastructure/logs"
PROJECT_LOG_DIR="$REPO_ROOT/.codebase-intelligence/code-graph/logs"
LOCAL_LOG="$REPO_ROOT/.codebase-intelligence/code-graph/update.log"

mkdir -p "$CENTRALIZED_LOG_DIR"
mkdir -p "$PROJECT_LOG_DIR"

# Project configuration
SCRIPT_START

cat >> "$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh" << CONFIG
PROJECT_NAME="$PROJECT_NAME"
GROUP="$GROUP"
DB_PROJECT="$DB_PROJECT"
DB_GROUP="$DB_GROUP"
CONFIG

cat >> "$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh" << 'SCRIPT_END'

# Update a single database
update_graph() {
    local db_name="$1"
    local repo_path="$2"
    local log_name="$(echo "$db_name" | sed 's/codegraph_//')"
    local level="$3"  # "project" or "group"

    echo "📊 Updating $db_name..."

    # Determine log location: project logs locally, group logs centrally
    local log_file
    if [ "$level" = "project" ]; then
        log_file="$PROJECT_LOG_DIR/${log_name}.log"
    else
        log_file="$CENTRALIZED_LOG_DIR/${log_name}.log"
    fi

    (
        cd "$CODE_GRAPH_ROOT"
        source venv/bin/activate

        export MEMGRAPH_DATABASE="$db_name"

        python -m codebase_rag.main start \
            --repo-path "$repo_path" \
            --update-graph \
            --no-confirm \
            >> "$log_file" 2>&1

        if [ $? -eq 0 ]; then
            echo "✅ $db_name updated successfully" | tee -a "$LOCAL_LOG"
        else
            echo "❌ $db_name update failed (check logs)" | tee -a "$LOCAL_LOG"
        fi
    )
}

# Create symlinks from project logs to centralized logs for group
create_log_symlinks() {
    if [ -n "$GROUP" ]; then
        local group_log="$PROJECT_LOG_DIR/${GROUP}.log"
        local group_target="$CENTRALIZED_LOG_DIR/${GROUP}.log"

        if [ ! -e "$group_log" ] && [ -f "$group_target" ]; then
            ln -sf "$group_target" "$group_log"
            echo "🔗 Created symlink: ${GROUP}.log → centralized"
        fi
    fi
}

# Main execution
echo "🔄 Code-Graph Update Started: $(date)" | tee -a "$LOCAL_LOG"

# Create symlinks for viewing all logs in one place
create_log_symlinks

# Update project graph
update_graph "$DB_PROJECT" "$REPO_ROOT" "project"

# Update group graph
if [ -n "$DB_GROUP" ] && [ -n "$GROUP" ]; then
    GROUP_PATH="$(dirname "$REPO_ROOT")"
    update_graph "$DB_GROUP" "$GROUP_PATH" "group"
fi

echo "✅ Code-Graph Update Complete: $(date)" | tee -a "$LOCAL_LOG"
SCRIPT_END

chmod +x "$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh"
log_success "Updated code-graph/update.sh with group support"

#
# Step 4: Build Group Graph
#
print_section "Building Group Graph"

GROUP_PATH="$(dirname "$PROJECT_PATH")"

log "Group path: $GROUP_PATH"
log "This will index all projects in: $GROUP_PATH"

echo ""
log "Building group graph... (monitor progress: tail -f $LOGS_DIR/${GROUP}.log)"

# Run the update script (it will update both project and group)
"$PROJECT_PATH/.codebase-intelligence/code-graph/update.sh" || {
    log_warning "Graph build had warnings (check logs)"
}

log_success "Group graph initialized"

#
# Step 5: Summary
#
print_header "✨ Group Setup Complete! ✨"

echo "Project: $PROJECT_NAME"
echo "Group: $GROUP"
echo ""
echo "📊 Graph Databases:"
echo "  • $DB_PROJECT (project)"
echo "  • $DB_GROUP (group - indexes all projects in parent directory)"
echo ""
echo "📝 Commands:"
echo "  Manual update: $PROJECT_PATH/.codebase-intelligence/code-graph/update.sh"
echo "  View graphs:   http://localhost:3000 (Memgraph Lab)"
echo "  View logs:"
echo "    Project: tail -f $PROJECT_PATH/.codebase-intelligence/code-graph/update.log"
echo "    Group:   tail -f $LOGS_DIR/${GROUP}.log"
echo ""

#
# Step 6: Update Project Registry
#
REGISTRY_FILE="$CODE_GRAPH_ROOT/infrastructure/registry/projects.toon"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S")

# Check current systems
CURRENT_SYSTEMS="code-graph"
if [ -d "$PROJECT_PATH/.codebase-intelligence/vector-search" ]; then
    CURRENT_SYSTEMS="code-graph, vector-search"
fi

# Remove existing entry for this project
if [ -f "$REGISTRY_FILE" ]; then
    grep -v "path: $PROJECT_PATH$" "$REGISTRY_FILE" > "$REGISTRY_FILE.tmp" || true
    mv "$REGISTRY_FILE.tmp" "$REGISTRY_FILE"
fi

# Append updated entry
cat >> "$REGISTRY_FILE" << ENTRY
	- name: $PROJECT_NAME
	  path: $PROJECT_PATH
	  group: $GROUP
	  systems: [$CURRENT_SYSTEMS]
	  databases: [$DB_PROJECT, $DB_GROUP]
	  initialized_at: $TIMESTAMP
ENTRY

log_success "Updated project registry"
