#!/usr/bin/env bash
# LaunchAgent installation script for graph-code
# Auto-generated on 2025-12-11T16:22:29.154434+00:00
# Do not edit this file manually - regenerate using the bootstrap command.

set -euo pipefail

SERVICE_NAME="graph-code"
PLIST_NAME="com.ai-agency.${SERVICE_NAME}.plist"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLIST_FILE="${SCRIPT_DIR}/service.plist"
LAUNCH_AGENTS_DIR="${HOME}/Library/LaunchAgents"
INSTALLED_PLIST="${LAUNCH_AGENTS_DIR}/${PLIST_NAME}"

log_info() {
    echo "[INFO] $*"
}

log_error() {
    echo "[ERROR] $*" >&2
}

log_success() {
    echo "[SUCCESS] $*"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    if [[ ! -f "${PLIST_FILE}" ]]; then
        log_error "service.plist not found at ${PLIST_FILE}"
        exit 1
    fi

    if [[ ! -d "${LAUNCH_AGENTS_DIR}" ]]; then
        log_info "Creating LaunchAgents directory..."
        mkdir -p "${LAUNCH_AGENTS_DIR}"
    fi

    if ! command -v /Users/hunter/code/ai_agency/shared/mcp-servers/code-graph-rag/.venv/bin/python &> /dev/null; then
        log_error "Python executable not found: /Users/hunter/code/ai_agency/shared/mcp-servers/code-graph-rag/.venv/bin/python"
        exit 1
    fi

    log_success "Prerequisites check passed"
}

unload_existing() {
    if launchctl list | grep -q "${PLIST_NAME%.plist}"; then
        log_info "Unloading existing LaunchAgent..."
        launchctl unload "${INSTALLED_PLIST}" 2>/dev/null || true
        log_success "Existing LaunchAgent unloaded"
    fi
}

install_plist() {
    log_info "Installing LaunchAgent..."
    cp "${PLIST_FILE}" "${INSTALLED_PLIST}"
    chmod 644 "${INSTALLED_PLIST}"
    log_success "LaunchAgent installed to ${INSTALLED_PLIST}"
}

load_agent() {
    log_info "Loading LaunchAgent..."
    launchctl load "${INSTALLED_PLIST}"
    log_success "LaunchAgent loaded"
}

verify_running() {
    log_info "Verifying service is running..."
    sleep 2

    if launchctl list | grep -q "${PLIST_NAME%.plist}"; then
        log_success "Service is running"

        log_info "Testing HTTP endpoint..."
        if curl -s -f "http://127.0.0.1:9001/health" > /dev/null 2>&1; then
            log_success "HTTP endpoint is accessible at http://127.0.0.1:9001/health"
        else
            log_error "HTTP endpoint not accessible yet. Check logs for startup errors."
            log_info "View logs with: tail -f /Users/hunter/Library/Logs/graph-code-*.log"
        fi
    else
        log_error "Service is not running. Check logs for errors:"
        log_info "  stdout: /Users/hunter/Library/Logs/graph-code-stdout.log"
        log_info "  stderr: /Users/hunter/Library/Logs/graph-code-stderr.log"
        exit 1
    fi
}

show_usage() {
    cat << EOF

LaunchAgent Installation Complete!

Service: ${SERVICE_NAME}
Endpoint: http://127.0.0.1:9001

Useful Commands:
  Status:     launchctl list | grep ${PLIST_NAME%.plist}
  Stop:       launchctl unload ${INSTALLED_PLIST}
  Start:      launchctl load ${INSTALLED_PLIST}
  Restart:    launchctl unload ${INSTALLED_PLIST} && launchctl load ${INSTALLED_PLIST}
  Uninstall:  launchctl unload ${INSTALLED_PLIST} && rm ${INSTALLED_PLIST}

Logs:
  stdout: /Users/hunter/Library/Logs/graph-code-stdout.log
  stderr: /Users/hunter/Library/Logs/graph-code-stderr.log
  View:   tail -f /Users/hunter/Library/Logs/graph-code-*.log

Health Check:
  curl http://127.0.0.1:9001/health

Available Tools:
  curl http://127.0.0.1:9001/tools

The service will automatically start on system boot and restart if it crashes.

EOF
}

main() {
    log_info "Installing LaunchAgent for ${SERVICE_NAME}..."
    echo

    check_prerequisites
    unload_existing
    install_plist
    load_agent
    verify_running

    echo
    show_usage
}

main "$@"